### ISSUE TITLE
c# RECV Count is always 0!

### ISSUE THREAD

**Issue by Vlandmist** [DaggerES/CLineTester#1]
I tested the python code and it works perfectly. clines are returned as valid/invalid
C# code, on the other hand, _always_ returns `recvCount == 0` 

sample:

```
byte[] receiveBytes = new byte[20];
var recvCount = socket.Receive(receiveBytes);

    if (recvCount > 0)
    {
          ReceiveBlock.cc_decrypt(receiveBytes, 20);
           // unreachable section
    }
```

I've tried on two different environments and the problem persists, can you please check? thanks

**Comment by gavazquez** [comment]
Thanks for reporting!

There was a bug in this lines:

byte[] pwd = new byte[password.Length];
Array.Copy(GetBytes(password), **pwd**, GetBytes(password).Length);
SendBlock.cc_encrypt(pwd, pwd.Length); //encript psw in cripto block

I uploaded the fix :)
