### ISSUE TITLE
Hello Help me please

### ISSUE THREAD

**Issue by docea37** [DaggerES/CLineTester#10]
> CLineTester-master/CSharp/CSharp.sln is missing from source code
> her is how can build it and try it
> 
> Start new C# .NET4 porject as ConsoleApplication and close it
> 
> Edit ConsoleApp1.csproj with notepad
> add this lines after **_Compile Include="Program.cs"**
> 
> ```
> <Compile Include="CcamMsg.cs" />
> <Compile Include="CcamClientInfo.cs" />
> <Compile Include="CcamServerInfo.cs" />
> <Compile Include="CcCardData.cs" />
> <Compile Include="CryptoBlock.cs" />
> <Compile Include="MsgTypes.cs" />
> ```
> 
> copy 6 files inside CSharp to where Program.cs is
> open project everything will be ok
> it`s ConsoleApplication not FormApplication
> 
> you can try convert it to vb.net its need hard work

Hi
@xcodrer Thank you for your help
I managed to run it as you said. but I was unable to add a forum and enter information.
https://www.dropbox.com/s/okztlix8jitfuqa/ConsoleApplication1.rar?dl=0

1 - I was able to get the server name, username and password typed in textbox1. but I'm having trouble with the port number.
2 - I want to print the positive result to textbox2 and the negative result to textbox3. how can I do that.
3 - Is it possible to hide the consol screen

**Comment by docea37** [comment]
string kelime = textBox1.Text;

            string[] parcalar;

            parcalar = kelime.Split(' ', ':', 'C');

            label1.Text = server = parcalar[3];

            label2.Text = parcalar[4];

            label3.Text = username = parcalar[5];

            label4.Text = password = parcalar[6];

            port = int.Parse(label2.Text);`

this is how I solved the port error.
the current problem is to hide the console and print the result from the console in textbox`

**Comment by docea37** [comment]
I have to close the form screen to get the output.
What should I do to print the output without closing the form
I could not print the output in the textbox

https://www.dropbox.com/s/okztlix8jitfuqa/ConsoleApplication1.rar?dl=0

**Comment by docea37** [comment]
Hi
How can I empty the class for multiple scans

**Comment by docea37** [comment]
hello @gavazquez 
codes scan once. In the second scan, even if the server is running, it looks closed.
is it possible to help with this?

**Comment by docea37** [comment]
[url=https://hizliresim.com/2f1npT][img]https://i.hizliresim.com/2f1npT.png[/img][/url]
[url=https://hizliresim.com/axWzyy][img]https://i.hizliresim.com/axWzyy.png[/img][/url]

**Comment by gavazquez** [comment]
Hi Sorry but you need to put the code in a github repo so I can have a look at it. Also it seems that your socket is closed. You should put it inside a "using" statement

**Comment by docea37** [comment]
hello @gavazquez

`using System;
using System.Windows.Forms;
using ConsoleApplication;
using System.Net.Sockets;
using System.Text;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.IO;
using System.Linq;


namespace test3
{

    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        public static List<CcCardData> Cards { get; } = new List<CcCardData>();

        private static bool retrieveCardInfo = true;
        public static string server;
        public static int port;
        public static string username;
        public static string password;
        public static string infoss;

        public static readonly CryptoBlock ReceiveBlock = new CryptoBlock();
        public static readonly CryptoBlock SendBlock = new CryptoBlock();
        public static Socket sckt = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
        [STAThread]

        private void button1_Click(object sender, EventArgs e)
        {
            if (textBox1.Text == "")
            {
                MessageBox.Show("Lütfen Cline girin");
                return;
            }
            
            string kelime = textBox1.Text;
            string []parcalar;
            parcalar = kelime.Split(' ', ':', 'C');
            server = label1.Text = parcalar[3];
            port = int.Parse(parcalar[4]);
            username = label3.Text = parcalar[5];
            password = label4.Text = parcalar[6];
            label2.Text = parcalar[4];
            
            try
                
            {
                
                sckt.SendTimeout = 300;
                sckt.ReceiveTimeout = 300;

                sckt.Connect(server, port);

                var helloBytes = new byte[16];
                sckt.Receive(helloBytes);
                Console.WriteLine("Received hello: " + Encoding.UTF8.GetString(helloBytes));

                if (!CheckConnectionChecksum(helloBytes, 16))
                {
                    throw new Exception("Wrong connection Checksum");
                }

                CryptoBlock.cc_crypt_xor(helloBytes);

                SHA1 sha = new SHA1Managed();
                var sha1Hash = sha.ComputeHash(helloBytes);

                //Init receive cripto block
                ReceiveBlock.cc_crypt_init(sha1Hash, 20);
                ReceiveBlock.cc_decrypt(helloBytes, 16);

                //Init send cripto block
                SendBlock.cc_crypt_init(helloBytes, 16);
                SendBlock.cc_decrypt(sha1Hash, 20);

                SendMessage(MsgTypes.MsgNoHeader, 20, sha1Hash); //Handshake

                byte[] userName = new byte[20];
                Array.Copy(GetBytes(username), userName, GetBytes(username).Length);
                SendMessage(MsgTypes.MsgNoHeader, 20, userName); //Send username in a padded array of 20 bytes

                byte[] pwd = new byte[password.Length];
                Array.Copy(GetBytes(password), pwd, GetBytes(password).Length);
                SendBlock.cc_encrypt(pwd, pwd.Length); //encript psw in cripto block

                byte[] cCcam = { Convert.ToByte('C'), Convert.ToByte('C'), Convert.ToByte('c'),
                    Convert.ToByte('a'), Convert.ToByte('m'), 0 };
                SendMessage(MsgTypes.MsgNoHeader, 6, cCcam); //Send "CCcam" with password encripted block

                try
                {
                    byte[] receiveBytes = new byte[20];
                    var recvCount = sckt.Receive(receiveBytes);

                    if (recvCount > 0)
                    {
                        ReceiveBlock.cc_decrypt(receiveBytes, 20);

                        var valid = Encoding.Default.GetString(receiveBytes).Replace("\0", "") == "CCcam";                 
                        string mesaj = textBox1.Text;
                        label6.Text=(mesaj);
                        

                        if (valid && retrieveCardInfo)
                        {
                            SendClientInfo();
                                
                            if (sckt.Connected)
                                ReadCardsInformation();
                                label8.Text = infoss;
                                listBox1.Items.Add(label6.Text + " # " + label8.Text);
                        }
                    }
                    else
                    {
                        string mesaj1 = textBox1.Text;
                        listBox2.Items.Add(mesaj1);
                    }
                }
                catch (Exception)
                {
                    string mesaj1 = textBox1.Text;
                    listBox2.Items.Add(mesaj1);
                }
            }
            catch (Exception)
            {
                string mesaj1 = textBox1.Text;
                listBox2.Items.Add(mesaj1);
            }
            sckt.Close();
            //textBox1.Text = ("");
            // textBox1.Focus();
        }
        private static void ReadCardsInformation()
        {
            while (true)
            {
                try
                {
                    var msgBytes = ReadMessage();
                    if (msgBytes != null)
                    {
                        var msg = new CcamMsg(msgBytes);
                        DecodeMessage(msg);
                    }
                }
                catch (Exception)
                {
                    return;
                }
            }
        }

        private static bool CheckConnectionChecksum(byte[] buf, int len)
        {
            if (len == 16)
            {
                byte sum1 = (byte)(buf[0] + buf[4] + buf[8]);
                byte sum2 = (byte)(buf[1] + buf[5] + buf[9]);
                byte sum3 = (byte)(buf[2] + buf[6] + buf[10]);
                byte sum4 = (byte)(buf[3] + buf[7] + buf[11]);

                var valid = (sum1 == buf[12]) && (sum2 == buf[13]) && (sum3 == buf[14]) && (sum4 == buf[15]);
                return valid;
            }
            return false;
        }
        private static byte[] GetBytes(string str)
        {
            byte[] bytes = new byte[str.Length * sizeof(char)];
            Buffer.BlockCopy(str.ToCharArray(), 0, bytes, 0, bytes.Length);
            return Encoding.ASCII.GetBytes(str);
        }

        #region Message sending

        public static void SendClientInfo()
        {
            var cliInfo = new byte[20 + 8 + 1 + 64];

            Array.Copy(GetBytes(username), cliInfo, GetBytes(username).Length); //20
            Array.Copy(CcamClientInfo.Nodeid, 0, cliInfo, 20, CcamClientInfo.Nodeid.Length); //8
            cliInfo[28] = 0;

            Array.Copy(GetBytes(CcamClientInfo.Version), 0, cliInfo, 29, GetBytes(CcamClientInfo.Version).Length); // 32
            Array.Copy(GetBytes(CcamClientInfo.Build), 0, cliInfo, 61, GetBytes(CcamClientInfo.Build).Length); // 32

            SendMessage(MsgTypes.MsgCliInfo, cliInfo);
        }

        public static int SendMessage(MsgTypes cmd, byte[] buf)
        {
            return SendMessage(cmd, buf.Length, buf);
        }

        public static int SendMessage(MsgTypes cmd, int len, byte[] data)
        {
            byte[] sendData;
            if (cmd == MsgTypes.MsgNoHeader)
            {
                sendData = new byte[len];
                Array.Copy(data, sendData, len);
            }
            else
            {
                // build command message
                sendData = new byte[4 + len];
                sendData[0] = 0;   // flags??
                sendData[1] = (byte)((int)cmd & 0xff);
                sendData[2] = (byte)(len >> 8);
                sendData[3] = (byte)(len & 0xff);
                if (len > 0)
                {
                    Array.Copy(data, 0, sendData, 4, len);
                }
            }

            SendBlock.cc_encrypt(sendData, len);

            try
            {
                return sckt.Send(sendData);
            }
            catch (Exception)
            {
                Console.WriteLine("Connection closed while sending");
                sckt.Close();
            }

            return -1;
        }

        #endregion

        #region Message receiveing

        public static byte[] ReadMessage()
        {
            if (sckt == null)
            {
                throw new IOException();
            }

            var header = new byte[4];
            sckt.Receive(header);
            ReceiveBlock.cc_decrypt(header, 4);
            var dataLength = (((header[2] & 0xe7) * 256) + header[3] & 0xff);
            if (dataLength == 0 || dataLength > (1024 - 2))
                return null;

            var data = new byte[dataLength];
            sckt.Receive(data);
            ReceiveBlock.cc_decrypt(data, dataLength);

            var fullData = new byte[4 + dataLength];
            Array.Copy(header, 0, fullData, 0, 4);
            Array.Copy(data, 0, fullData, 4, dataLength);

            return fullData;
        }

        public static void DecodeMessage(CcamMsg msg)
        {
            switch (msg.CommandTag)
            {
                case MsgTypes.MsgCardDel:
                case MsgTypes.MsgCliInfo:
                    break;
                case MsgTypes.MsgCardAdd:
                    if ((msg.CustomData[20] & 0xff) > 0)
                    {
                        var card = new CcCardData
                        {
                            RemoteId = string.Join("", msg.CustomData.Take(4).Select(s => s.ToString("X"))),
                            Uphops = (msg.CustomData[10] & 0xff) + 1,
                            NodeId = msg.CustomData.Skip(22 + msg.CustomData[20] * 7).Take(8 + 22 + msg.CustomData[20] * 7).ToArray(),
                            CaId = (((msg.CustomData[8]) << 8) | (msg.CustomData[9])).ToString("X"),
                            ProviderCount = msg.CustomData[20] & 0xff,
                            Serial = msg.CustomData.Skip(12).Take(12 + 8).ToArray()
                        };

                        var providers = new int[msg.CustomData[20]];
                        for (var i = 0; i < msg.CustomData[20]; i++)
                        {
                            var provid = ((msg.CustomData[21 + i * 7] & 0xff) << 16) |
                                ((msg.CustomData[22 + i * 7] & 0xff) << 8) |
                                (msg.CustomData[23 + i * 7] & 0xff);

                            providers[i] = provid;
                        }
                        card.Providers = providers.Select(p => p.ToString("X")).ToArray();
                        //Console.WriteLine($"Card: {card}");
                        //MessageBox.Show($"Card: {card}");
                        Cards.Add(card);
                    }
                    break;
                case MsgTypes.MsgSrvInfo:

                    CcamServerInfo.NodeId = string.Join("", msg.CustomData.Take(8).Select(n => n.ToString("X")));
                    CcamServerInfo.Version = Encoding.Default.GetString(msg.CustomData.Skip(8).Take(31).ToArray());
                    CcamServerInfo.Build = Encoding.Default.GetString(msg.CustomData.Skip(40).Take(31).ToArray());

                   // MessageBox.Show($"Version:{CcamServerInfo.Version.Replace("\0", "").Trim()} " +
                     //                $"Build: {CcamServerInfo.Build.Trim()}");
                    infoss = ($"{CcamServerInfo.Version.Replace("\0", "").Trim()} " +
                                     $"- {CcamServerInfo.Build.Trim()}");
                    break;
                case MsgTypes.MsgEcmNok1:
                case MsgTypes.MsgEcmNok2:
                    sckt.Close();
                    break;
                default:
                    sckt.Close();
                    throw new IOException();
            }
            sckt.Close();
        }

        #endregion

        private void button2_Click(object sender, EventArgs e)
        {
            Form2 form2sec = new Form2();
            form2sec.Show();
            
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            label1.Visible = false;
            label2.Visible = false;
            label3.Visible = false;
            label4.Visible = false;
            label6.Visible = false;
            label8.Visible = false;



        }
    }


    }

`

**Comment by docea37** [comment]
[url=https://hizliresim.com/DPgQpE][img]https://i.hizliresim.com/DPgQpE.png[/img][/url]

**Comment by gavazquez** [comment]
I didn't do the card id part tbh as that was made by Arsi. The idea of this code was only to test if a server works or not and nothing else

**Comment by Systemub** [comment]
hi dear docea37;
first step generic counter definition.
second step scope by card writeline in the counter added
three step main method scope area in the write the counter.

warning: up steps for console applications formats

**Comment by Amadeus23000** [comment]
Totally unrelated. is there anyway you could make cccam descrambler as a plugin for VLC  to use it with sat2ip rtp streams?

**Comment by lumkat** [comment]
hello please help what is cccam multi socket reading code
