### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by docea37** [DaggerES/CLineTester#2]
hi

how to online web control cline/nline active. Without satellite receiver connection
I novice in these matters
help me please

**Comment by gavazquez** [comment]
You need programming knowledge to use my scripts. Otherwise use testious.com

**Comment by docea37** [comment]
http://taklaking.tk/cccam/ (index.php - check.php --- css folder -fonts folder - js folder ---- cccam.js)

copy all files but it does not work

**Comment by gavazquez** [comment]
You are programming in PHP and my scripts are in Python, Java and C#.
You need to adapt my code to your language (PHP) or find a way to make PHP communicate with python/java/C#

**Comment by lumkat** [comment]
hello please help what is cccam multi socket reading code
