### ISSUE TITLE
Feature: load list of cards

### ISSUE THREAD

**Issue by arsi-apli** [DaggerES/CLineTester#3]
I have added feature to load list of cards for the java version..

[cline_tester_java.zip](https://github.com/DaggerES/CLineTester/files/981521/cline_tester_java.zip)

**Comment by gavazquez** [comment]
Awesome!!! Thanks! I will have a look and try to adapt it to the C# and Python versions next week

**Comment by arsi-apli** [comment]
I have found one problem,  if is cccam  server unavailable, it waits for an infinite timeout..
change:
```java
socket = new Socket(this.host, this.port);
socket.setSoTimeout(3000);
```
to:
```java
socket = new Socket();
socket.connect(new InetSocketAddress(this.host, this.port), 3000); //connect timeout
socket.setSoTimeout(3000);
```

**Comment by arsi-apli** [comment]
final version ;)

```java
//Created by Dagger -- https://github.com/DaggerES
//mod by ArSi
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.net.*;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CCcamConnector {

    public static final int MSG_CLI_INFO = 0;
    public static final int MSG_ECM_CW = 1;
    public static final int MSG_EMM_ACK = 2;
    public static final int MSG_CARD_DEL = 4;
    public static final int MSG_CMD_05 = 5;
    public static final int MSG_KEEPALIVE = 6;
    public static final int MSG_CARD_ADD = 7;
    public static final int MSG_SRV_INFO = 8;

    public static final int MSG_CMD_0A = 10;
    public static final int MSG_CMD_0B = 11;
    public static final int MSG_CMD_0C = 12;
    public static final int MSG_CMD_0D = 13;
    public static final int MSG_CMD_0E = 14;
    public static final int MSG_NEW_CARD_SIDINFO = 15;

    public static final int MSG_ECM_NOK1 = 254;
    public static final int MSG_ECM_NOK2 = 255;

    public static final int MSG_SLEEPSEND = 128;
    public static final int MSG_CACHE_PUSH = 129;

    public static final int MSG_NO_HEADER = 65535;

    private String host, user, password;
    private int port;
    private CryptoBlock recvblock;
    private CryptoBlock sendblock;
    private Socket socket;
    private DataInputStream is;
    private BufferedOutputStream os;
    private Map cardMap = new HashMap();

     public CCcamConnector(String host, int port, String username, String psw)
            throws UnknownHostException, IOException {

        this.host = host;
        this.port = port;
        this.user = username;
        this.password = psw;


        socket = new Socket();
        socket.connect(new InetSocketAddress(this.host, this.port), 2000);
        socket.setSoTimeout(3000);
        is = new DataInputStream(socket.getInputStream());
        os = new BufferedOutputStream(socket.getOutputStream());
    }

    public synchronized int SendMsg(int len, byte[] buf) throws IOException {
        byte[] netbuf;
        netbuf = new byte[len];
        System.arraycopy(buf, 0, netbuf, 0, len);
        sendblock.cc_encrypt(netbuf, len);

        try {
            os.write(netbuf);
            os.flush();
            return len;
        } catch (IOException e) {
            socket.close();
        }
        return -1;
    }

    public synchronized int cc_msg_send(int cmd, int len, byte[] buf) {
        byte[] netbuf;

        if (cmd == MSG_NO_HEADER) {
            netbuf = new byte[len];
            System.arraycopy(buf, 0, netbuf, 0, len);
        } else {
            netbuf = new byte[4 + len];
            // build command message
            netbuf[0] = 0;   // flags??
            netbuf[1] = (byte) (cmd & 0xff);
            netbuf[2] = (byte) (len >> 8);
            netbuf[3] = (byte) (len & 0xff);
            if (len > 0) {
                System.arraycopy(buf, 0, netbuf, 4, len);
            }
            len += 4;
        }
        sendblock.cc_encrypt(netbuf, len);

        try {
            os.write(netbuf);
            os.flush();
            return len;
        } catch (IOException e) {
        }
        return -1;
    }

    public void cc_send_client_info() {
        byte[] buf = new byte[20 + 8 + 1 + 64];
        System.arraycopy(user.getBytes(), 0, buf, 0, user.length()); // 20
        System.arraycopy(CcData.nodeid, 0, buf, 20, 8);
        buf[28] = 0;
        System.arraycopy(CcData.version.getBytes(), 0, buf, 29, CcData.version.length()); // 32
        System.arraycopy(CcData.build.getBytes(), 0, buf, 61, CcData.build.length()); // 32
        cc_msg_send(MSG_CLI_INFO, 20 + 8 + 1 + 64, buf); // send 'CCcam' xor w/ pwd
    }

    public byte[] readMessage() throws IOException {
        if (is == null) {
            throw new IOException();
        }

        int len = 4;
        byte[] header = new byte[4];
        byte[] data = null;
        is.read(header, 0, 4);
        recvblock.cc_decrypt(header, len);
        int datalen = (((header[2] & 0xe7) * 256) + header[3] & 0xff);
        if (datalen != 0) {  // check if any data is expected in msg
            if (datalen > (1024 - 2)) {
                return null;
            }
            data = new byte[datalen];
            is.read(data, 0, datalen);
            recvblock.cc_decrypt(data, datalen);
        }
        byte[] netbuf = new byte[4 + datalen];
        System.arraycopy(header, 0, netbuf, 0, 4);
        if (datalen > 0) {
            System.arraycopy(data, 0, netbuf, 4, datalen);
        }
        return netbuf;
    }

    private byte[] nodeid = new byte[8];
    private String version = new String();
    private String build = new String();

    private void decodeMesg(CCCamMsg msg) throws IOException {
        byte[] data = msg.getCustomData();
        switch (msg.getCommandTag()) {
            case MSG_CLI_INFO:
                break;

            case MSG_SRV_INFO:
                System.arraycopy(msg.getCustomData(), 0, nodeid, 0, 8);
                version = new String(msg.getCustomData(), 8, 31);
                build = new String(msg.getCustomData(), 40, 31);
                break;

            case MSG_ECM_CW:
                socket.close();
                throw new IOException();

            case MSG_ECM_NOK1:
            case MSG_ECM_NOK2:
                socket.close();

            case MSG_KEEPALIVE:
                socket.close();
                throw new IOException();

            case MSG_CARD_DEL:
                break;

            case MSG_CARD_ADD:
                if ((data[20] & 0xff) > 0) {
                    CcCardData card = new CcCardData();
                    card.setShareId(Arrays.copyOf(data, 4));
                    card.setUpHops((data[10] & 0xff) + 1);
                    card.setNodeId(Arrays.copyOfRange(data, 22 + data[20] * 7, 8 + 22 + data[20] * 7));
                    card.setCaId(((data[8] & 0xff) << 8) | (data[9]) & 0xff);
                    card.setNumberOfProviders(data[20] & 0xff);
                    card.setSerial(Arrays.copyOfRange(data, 12, 12 + 8));

                    int[] providers = new int[data[20]];
                    for (int i = 0; i < data[20]; i++) {
                        int provid = ((data[21 + i * 7] & 0xff) << 16) | ((data[22 + i * 7] & 0xff) << 8) | (data[23 + i * 7] & 0xff);
                        providers[i] = provid;
                    }
                    card.setProviders(providers);
                    cardMap.put(card.getShareId(), card);
                }
                break;
            default:
                socket.close();
                throw new IOException();
        }
    }

    public class CCCamMsg {

        byte[] raw;
        byte[] fixedData;
        byte[] customData;
        int commandTag;
        int dataLength;

        public CCCamMsg(byte[] raw) {
            this.raw = raw;
        }

        public byte[] getRaw() {
            return raw;
        }

        public byte[] getFixedData() {
            return fixedData;
        }

        public byte[] getCustomData() {
            return customData;
        }

        public int getCommandTag() {
            return commandTag;
        }

        public int getDataLength() {
            return dataLength;
        }

    }

    public CCCamMsg parseCCcam(byte[] raw) {
        try {
            CCCamMsg msg = new CCCamMsg(raw);
            msg.commandTag = raw[1] & 0xff;
            // Header
            msg.fixedData = new byte[4];
            System.arraycopy(raw, 0, msg.fixedData, 0, 4);
            // Data
            msg.dataLength = (raw[2] & 0x0F) * 256 + (raw[3] & 0xFF);
            msg.customData = new byte[msg.dataLength];

            System.arraycopy(raw, 4, msg.customData, 0, msg.dataLength);
            return msg;
        } catch (Exception e) {
            return null;
        }

    }

    public List<CcCardData> TestCline() throws Exception {
        try {

            byte[] helloBytes = new byte[16];
            is.readFully(helloBytes);

            CryptoBlock.cc_crypt_xor(helloBytes);  // XOR init bytes with 'CCcam'

            MessageDigest md;
            md = MessageDigest.getInstance("SHA-1");
            byte[] sha1hash = new byte[20];
            sha1hash = md.digest(helloBytes);

            recvblock = new CryptoBlock();
            recvblock.cc_crypt_init(sha1hash, 20);
            recvblock.cc_decrypt(helloBytes, 16);

            sendblock = new CryptoBlock();
            sendblock.cc_crypt_init(helloBytes, 16);
            sendblock.cc_decrypt(sha1hash, 20);

            SendMsg(20, sha1hash);//send crypted hash to server

            byte[] userBuf = new byte[20];
            System.arraycopy(user.getBytes(), 0, userBuf, 0, user.length());
            SendMsg(20, userBuf);//send username to server

            byte[] pwd = new byte[password.length()];
            System.arraycopy(password.getBytes(), 0, pwd, 0, password.length());
            sendblock.cc_encrypt(pwd, password.length()); //encript the password

            byte[] CCcam = {'C', 'C', 'c', 'a', 'm', 0};
            SendMsg(6, CCcam); //But send CCcam\0

            byte[] rcvBuf = new byte[20];
            is.read(rcvBuf);
            recvblock.cc_decrypt(rcvBuf, 20);
            //check if received string after decription equals "CCcam"
            if (Arrays.equals(CCcam, Arrays.copyOf(rcvBuf, 6))) {
                //CCLine is correct!!!!
                cc_send_client_info();
                while (true) {
                    try {
                        byte[] readMessage = readMessage();
                        if (readMessage != null) {
                            CCCamMsg parseCCcam = parseCCcam(readMessage);
                            if (parseCCcam != null) {
                                decodeMesg(parseCCcam);
                            }
                        }
                    } catch (IOException iOException) {
                        return new ArrayList<>(cardMap.values());
                    }
                }

            }
        } catch (Exception e) {
        }
        socket.close();
        is.close();
        os.close();
        return new ArrayList<>();
    }
}

```

**Comment by gavazquez** [comment]
Uploaded your code and the C# version, hope to have the python version soon too!

**Comment by mdmiko** [comment]
can you give a check? I need some advice to list cards



#!/usr/bin/env python
# -*- coding: utf-8 -*- 
#Created by Dagger -- https://github.com/gavazquez

import CriptoBlock
import sys
import binascii

recvblock = CriptoBlock.CryptographicBlock()
sendblock = CriptoBlock.CryptographicBlock()

def TestCline(cline):
    import socket, re, sys, array, time, select

    returnValue = False
    regExpr = re.compile('[C]:\s*(\S+)+\s+(\d*)\s+(\S+)\s+([\w.-]+)')
    match = regExpr.search(cline)

    if match is None:
        return False;

    testSocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_IP)
    testSocket.settimeout(30) #timeout of 30 seconds

    host = str(match.group(1))
    port = int(match.group(2))
    username = str(match.group(3))
    password = str(match.group(4))
    
    try:
        ip = socket.gethostbyname(host)
        testSocket.connect((ip, port))

        DoHanshake(testSocket) #Do handshake with the server

        try:
            userArray = GetPaddedUsername(username)
            sendcount = SendMessage(userArray, len(userArray), testSocket) #Send the username
            
            passwordArray = GetPaddedPassword(password)
            sendblock.Encrypt(passwordArray, len(passwordArray)) #We encript the password
    
            #But we send "CCCam" with the password encripted CriptoBlock
            cccamArray = GetCcam()
            sendcount = SendMessage(cccamArray, len(cccamArray), testSocket)

            receivedBytes = bytearray(20)
            recvCount = testSocket.recv_into(receivedBytes, 20)

            if recvCount > 0:
                recvblock.Decrypt(receivedBytes, 20)
                if (receivedBytes.decode("ascii").rstrip('\0') == "CCcam"):
                    cc_send_client_info(username)
                    i = 0
                    while i < 10:
                        readmsg = readMessage(testSocket)
                        if readmsg is not None:
                            print("[DEBUG] ReadMesg ok")
                            #parse = ParseCCcam(readmsg)
                            #if parse is not None:
                            #    decodeMesg(parseCCcam)
                        i = i +1
                        print "------------------------------"

                    print("[INFO]  SUCCESS! working cline: " + cline)
                    #fh = open("mamt.txt", "a")
                    #fh.write(cline + "\n")
                    #fh.close
                    returnValue = True
                else:
                    print("Wrong ACK received!")
                    returnValue = False
            else:
                print("Bad username/password for cline: " + cline)
                returnValue = False

        except:
            print("Bad username/password for cline: " + cline)
            returnValue = False
    except:
        print("Error while connecting to cline: " + cline)

    testSocket.close()
    return returnValue

def GetPaddedUsername(userName):
    import array

    #We create an array of 20 bytes with the username in it as bytes and padded with 0 behind
    #Like: [23,33,64,13,0,0,0,0,0,0,0...]
    userBytes = array.array("B", userName)
    userByteArray = FillArray(bytearray(20), userBytes)

    return userByteArray

def GetCcam():
    import array

    #We create an array of 6 bytes with the "CCcam\0" in it as bytes
    cccamBytes = array.array("B", "CCcam") 
    cccamByteArray = FillArray(bytearray(6), cccamBytes)
    return cccamByteArray

def GetPaddedPassword(password):
    import array

    #We create an array of with the password in it as bytes
    #Like: [23,33,64,13,48,78,45]
    passwordBytes = array.array("B", password)
    passwordByteArray = FillArray(bytearray(len(password)),passwordBytes)

    return passwordByteArray
    
def DoHanshake(socket):
    import hashlib, array, CriptoBlock

    random = bytearray(16)
    socket.recv_into(random, 16) #Receive first 16 "Hello" random bytes
    #print "Hello bytes: " + random

    random = CriptoBlock.Xor(random); #Do a Xor with "CCcam" string to the hello bytes

    sha1 = hashlib.sha1()
    sha1.update(random)
    sha1digest = array.array('B', sha1.digest()) #Create a sha1 hash with the xor hello bytes
    sha1hash = FillArray(bytearray(20), sha1digest)

    recvblock.Init(sha1hash, 20) #initialize the receive handler
    recvblock.Decrypt(random, 16)

    sendblock.Init(random, 16) #initialize the send handler
    sendblock.Decrypt(sha1hash, 20)

    rcount = SendMessage(sha1hash, 20, socket) #Send the a crypted sha1hash!    
    
def SendMessage(data, len, socket):
    buffer = FillArray(bytearray(len), data)
    sendblock.Encrypt(buffer, len)
    rcount = socket.send(buffer)
    return rcount

def FillArray(array, source):
    if len(source) <= len(array):
        for i in range(0, len(source)):
            array[i] = source[i]
    else:
        for i in range(0, len(array)):
            array[i] = source[i]
    return array

def DoCardRequest(myusername, mynodeid, myversion, mybuild):
    import array

    buf[28] = str("0").encode()
    versionArray = FillArray(bytearray(len(myversion)),array.array("B", myversion))
    buf.append(versionArray)
    buildArray = FillArray(bytearray(len(mybuild)),array.array("B", mybuild))
    buf.append(buildArray)
    return buf

def ParseCCcam(raw):
    import array

    print("[DEBUG] ParseCCcam start")
    try:
        #new CCCcamMsg(raw)
        commandTag = raw[1] & 0xFF
        fixedData = bytearray(4)
        arrayCopy(raw, 0, fixedData, 0, 4)
        dataLength = ((raw[2] & 0xF) * 256 + (raw[3] & 0xFF))
        customData = bytearray(dataLength)
        arrayCopy(raw, 4, customData, 0, dataLength)
        return raw
    except:
        return None

def readMessage(socket):
    print("[DEBUG] readMessage start")
    if socket == None:
        print("ERRORE: socket vuoto")
        return null

    header = bytearray(4)
    count = socket.recv_into(header, 4)
    recvblock.Decrypt(header, 4)
    datalen = (((header[2] & 0xe7) * 256) + header[3] & 0xff)
    #if (dataLength == 0 or dataLength > (1024 - 2)):
    #    return None

    data = bytearray(datalen)
    count = socket.recv_into(data, datalen)
    recvblock.Decrypt(data, datalen)

    netbuf = bytearray(4 + datalen)
    arrayCopy(header, 0, netbuf, 0, 4)
    arrayCopy(data, 0, netbuf, 4, datalen)
    
    print("[DEBUG] header: {} datalen: {} data: {}".format(header, datalen, data))
    return netbuf

def int2bytes(i):
    hex_string = '%x' % i
    n = len(hex_string)
    return binascii.unhexlify(hex_string.zfill(n + (n & 1)))

def cc_msg_send(cmd, len, buf):
    try:
        print("[DEBUG] def: cc_msg_send")
        print(int2bytes(0))

        netbuf = bytearray(4 + len)

        netbuf[0] = bytes(b"0") # 0
        netbuf[1] = cmd & 0xff #cmd & 0xFF
        netbuf[2] = len >> 8 #len >> 8
        netbuf[3] = len & 0xff #len & 0xFF -- len = 93

        if (len > 0):
            arrayCopy(buf, 0, netbuf, 4, len)
        len = len + 4
        print("[DEBUG] netbuf: " + netbuf)
        sendblock.Encrypt(netbuf, len)
        return len
    except:
        print("[-------ERROR-------] cc_send_msg")
        return -1;

def cc_send_client_info(u):
    print("[DEBUG] def: cc_send_client_info")
    buf = bytearray(93)
    myUser = u
    myNodeId = "12345678"
    myVersion = "2.0.11"
    myBuild = "2892"
    
    buf[0:19] = bytearray(myUser, "ascii") #20
    buf[20:27] = bytearray(myNodeId, "ascii") #8
    buf[28] = bytes(b"0")
    buf[29:len(myVersion)] = bytearray(myVersion, "ascii") #32
    buf[61:len(myBuild)] = bytearray(myBuild, "ascii") #32
    cc_msg_send(0, 93, buf)
    print("[DEBUG] buf: " + buf)

def decodeMesg(msg):
        print "questa funzione dovrebbe solo estrarre dati dalla stringa"

#Utility
def arrayCopy(src, srcPos, dest, destPos, length):
    for i in range(length):
        dest[i + destPos] = src[i + srcPos]
