### ISSUE TITLE
Error while connecting to cline

### ISSUE THREAD

**Issue by Bo-M** [DaggerES/CLineTester#6]
When i test cline that i know is working, i get: Error while connecting to cline. I am using win7, python 3.6.3, it has something to do with handshake but i don't know what.

**Comment by gavazquez** [comment]
Probably because the cline server is out. Try to do a PING

**Comment by Bo-M** [comment]
The server is fine, ping is around 50ms. I tried with few that i know are working, but on every i get Error while connecting to cline, here is one that is working now 'C: server6.fastcccam.tv 12000 fstwb70877 hfy59jhls' if i try it on testionus it shows it works, but when i try with tester it says 'Error while connecting to cline: C: server6.fastcccam.tv 12000 fstwb70877 hfy59jhls'

**Comment by gavazquez** [comment]
You can try increasing the timeout, unfortunately I'm not in a computer at the moment but the python code is quite simple

is just touching this line:

https://github.com/gavazquez/CLineTester/blob/master/Python/CCcamTester.py#L21
