### ISSUE TITLE
Cryptoblock logic

### ISSUE THREAD

**Issue by brigantino2** [DaggerES/CLineTester#7]
Hi Gabriel,
I am currently writing an utility in python to test CCcam servers response and automatically generate a list for Hadu plugin.
I have found your project and this helped me a lot. I have rewritten and adapted part of your code to my needs (it's currently here https://github.com/brigantino2/clines-hadu/tree/initial). 
I have rewritten the cryptoblock part, but it's quite obscure to me. Do you have any resource or hint you can give to help me understand the way cryptoblock encoding/decoding works?
Thanks!

**Comment by gavazquez** [comment]
Hi!
Unfortunately I based my code on other stuff I've found, I tried to make it as clear as possible but that part is complex as is the cryto part and neither I fully understand it :(

**Comment by brigantino2** [comment]
I see :) I will try to look for something around, thank you anyway!
