### ISSUE TITLE
Hello Help me please

### ISSUE THREAD

**Issue by docea37** [DaggerES/CLineTester#9]
hello can you help me complete this project
I have some vb.net knowledge. I do not know c #

**Comment by xcodrer** [comment]
CLineTester-master/CSharp/CSharp.sln is missing from source code
her is how can build it and try it

Start new C# .NET4  porject as ConsoleApplication and close it

Edit ConsoleApp1.csproj with notepad
add this lines after **_Compile Include="Program.cs"**

    <Compile Include="CcamMsg.cs" />
    <Compile Include="CcamClientInfo.cs" />
    <Compile Include="CcamServerInfo.cs" />
    <Compile Include="CcCardData.cs" />
    <Compile Include="CryptoBlock.cs" />
    <Compile Include="MsgTypes.cs" />

copy 6 files inside CSharp to where Program.cs is
open project everything will be ok
it`s ConsoleApplication not FormApplication

you can try convert it to vb.net its need hard work

**Comment by docea37** [comment]
> CLineTester-master / CSharp / CSharp.sln kaynak kodundan eksik,
> onu nasıl oluşturabilir ve deneyebilir
> 
> ConsoleApplication olarak yeni C # .NET4 porjectini başlatın ve kapatın
> 
> Düzenleme ConsoleApp1.csproj not defteri ile
> sonra bu satırları ekleyin **_Compile "Program.cs" Dahil =**
> 
> ```
> <Compile Include="CcamMsg.cs" />
> <Compile Include="CcamClientInfo.cs" />
> <Compile Include="CcamServerInfo.cs" />
> <Compile Include="CcCardData.cs" />
> <Compile Include="CryptoBlock.cs" />
> <Compile Include="MsgTypes.cs" />
> ```
> 
> CSharp içindeki 6 dosyayı Program.cs'in
> açık olduğu yere kopyalayın proje her şey yoluna girecek
> KonsolUygulama FormApplication değil
> 
> vb.net zor iş dönüştürmek için deneyebilirsiniz

**Comment by docea37** [comment]
hello

**Comment by docea37** [comment]
> CLineTester-master/CSharp/CSharp.sln is missing from source code
> her is how can build it and try it
> 
> Start new C# .NET4 porject as ConsoleApplication and close it
> 
> Edit ConsoleApp1.csproj with notepad
> add this lines after **_Compile Include="Program.cs"**
> 
> ```
> <Compile Include="CcamMsg.cs" />
> <Compile Include="CcamClientInfo.cs" />
> <Compile Include="CcamServerInfo.cs" />
> <Compile Include="CcCardData.cs" />
> <Compile Include="CryptoBlock.cs" />
> <Compile Include="MsgTypes.cs" />
> ```
> 
> copy 6 files inside CSharp to where Program.cs is
> open project everything will be ok
> it`s ConsoleApplication not FormApplication
> 
> you can try convert it to vb.net its need hard work

Hi
Thank you for your help
I managed to run it as you said. but I was unable to add a forum and enter information.
https://www.dropbox.com/s/okztlix8jitfuqa/ConsoleApplication1.rar?dl=0

**Comment by xcodrer** [comment]
I can do it if source code vb.net

**Comment by lumkat** [comment]
> vb.net kaynak kodu varsa yapabilirim

hello please help what is cccam multi socket reading code
